# Generated by Django 3.2.5 on 2021-07-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ranking',
            field=models.BigIntegerField(default=0, verbose_name='Ranking'),
        ),
    ]
