# Generated by Django 3.2.5 on 2021-07-15 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_question_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.PositiveIntegerField(choices=[(0, 'Sin Responder'), (1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Regular'), (4, 'Alto'), (5, 'Muy Alto')], default=0, verbose_name='Respuesta'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, null=True, verbose_name='Like')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='survey.question', verbose_name='Pregunta')),
            ],
        ),
    ]
